### ISSUE TITLE
Error in function (type, msg, asError = TRUE)  :

### ISSUE THREAD

**Issue by Weiming113** [swaruplabUCI/ArchRtoSignac#25] opened 2023-08-09 20:46 UTC
Hello,

I was trying to update the package of Seurat. But it gave a error information at the "getAnnotation(reference = EnsDb.Hsapiens.v86, refversion = "hg38") " step. 
> annotations <- getAnnotation(reference = EnsDb.Hsapiens.v86, refversion = "hg38") # "UCSC" is the default style to change to but can be changed with argument seqStyle
[1] "In Progress:"
[1] "Extract genomic ranges from EnsDb object and prepare annotation"
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=21s  
Error in function (type, msg, asError = TRUE)  :

**Comment by rootze** [comment] 2023-08-09 21:22
> Hello,
> 
> I was trying to update the package of Seurat. But it gave a error information at the "getAnnotation(reference = EnsDb.Hsapiens.v86, refversion = "hg38") " step.
> 
> > annotations <- getAnnotation(reference = EnsDb.Hsapiens.v86, refversion = "hg38") # "UCSC" is the default style to change to but can be changed with argument seqStyle
> > [1] "In Progress:"
> > [1] "Extract genomic ranges from EnsDb object and prepare annotation"
> > |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=21s
> > Error in function (type, msg, asError = TRUE) 

Hello @Weiming113 I am not sure what happened to Seurat updating and what you are running. Is this error happened during updating Seurat? Please provide what version of the packages (ArchRtoSignac, Seurat, and Signac) you are using. 

Additionally, I cannot reproduce your error in my terminal. It works fine for me. 
```
> annotations <- getAnnotation(reference = EnsDb.Hsapiens.v86, refversion = "hg38")
[1] "In Progress:"
[1] "Extract genomic ranges from EnsDb object and prepare annotation"
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=01m 55s
[1] "Return Annotation"
```
I believe this error is an R programming error rather than a package running error, so this is a bit beyond the scope.

**Comment by Weiming113** [comment] 2023-08-09 21:33
> packageVersion("Seurat")
[1] '4.9.9.9058'
> packageVersion("Signac")
[1] '1.10.9001'
> packageVersion("ArchR")
[1] '1.0.2'
> packageVersion("stringr")
[1] '1.5.0'
> packageVersion("ArchRtoSignac")
[1] '1.0.3'
> packageVersion("EnsDb.Hsapiens.v86")
[1] '2.99.0'
> 
Here is the package version I used in my project.

**Comment by Weiming113** [comment] 2023-08-09 22:25
It still gives this error information. Each package is installed correctly. Don't know where is the problem.

**Comment by rootze** [comment] 2023-08-09 23:37
@Weiming113 I have not started with Seurat V5. They just made this new version, we strongly suggest using Seurat v4 at this time. [`1] '4.9.9.9058' `, this is the new version V5, which is the beta version. 
```
packageVersion("Seurat")
[1] '4.9.9.9058'
```
Version 4.3 should work on almost everything before. https://github.com/satijalab/seurat

I don't know if that makes a difference. But you can give it a try. Once again, I believe this error is an R programming error rather than a package running error, so this is a bit beyond the scope of what we do. I will close this issue again. Thank you for trying the `ArchRtoSignac` package. Good luck with everything!

**Closed by rootze** 2023-08-09 23:37 UTC
